apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJaRE5pZFRrNVpYSTZaMmh3WDB0eGVWUjJVV1JuTmxOdVNtOVpORXBMWld4TFkwRlNOV3RXYUdWdlNUTjRUWEZhUXc9PSIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson